_target_: pie_core.AutoAnnotationPipeline.from_pretrained
pretrained_model_name_or_path: ???
show_progress_bar: true
# uncomment for "old" PyTorch-IE models that do not have a pipeline_type key in their config.json
# pipeline_type: pytorch-ie
