_target_: pytorch_lightning.Trainer

default_root_dir: ${paths.output_dir}
enable_model_summary: False

gpus: 0

min_epochs: 1
max_epochs: 10

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null
