# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# save cfg to pickle for reproducibility
# callbacks:
#   save_job_info:
#     _target_: hydra.experimental.callbacks.PickleJobInfoCallback

callbacks:
  save_job_return:
    _target_: src.hydra_callbacks.SaveJobReturnValueCallback
    integrate_multirun_result: true
    filenames:
      - job_return_value.json
      - job_return_value.md
    multirun_aggregator_blacklist: ["min", "25%", "50%", "75%", "max"]

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${pipeline_type}/runs/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${paths.log_dir}/${pipeline_type}/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.num}
