_target_: src.taskmodules.SimpleTransformerTextClassificationTaskModule

#tokenizer_name_or_path: ${transformer_model} # transformer_model is specified in config_rel.yaml
tokenizer_name_or_path: bert-base-uncased
