_target_: src.models.transformer_token_classification.TransformerTokenClassificationModel.from_taskmodule

#model_name_or_path: ${transformer_model} # transformer_model is specified in config_rel.yaml
model_name_or_path: bert-base-uncased
