add_partitions:
  _processor_: pie_datasets.DatasetDict.map
  function:
    # see this for further information and options:
    # https://github.com/ArneBinder/pie-datasets/blob/main/src/pie_datasets/document/processing/regex_partitioner.py
    _target_: pie_datasets.document.processing.RegexPartitioner
    pattern: ???
