add_candidate_relations:
  _processor_: pytorch_ie.DatasetDict.map
  function:
    _target_: pie_utils.document.processors.CandidateRelationAdder
    #partition_layer: partitions
    #max_distance: 177
