add_candidate_relations:
  _processor_: pytorch_ie.DatasetDict.map
  function:
    # see this for further information and options:
    # https://github.com/ArneBinder/pie-utils/blob/main/src/pie_utils/document/processors/candidate_relation_adder.py
    _target_: pie_utils.document.processors.CandidateRelationAdder
    #partition_layer: partitions
    #max_distance: 177
