add_partitions:
  _processor_: pytorch_ie.DatasetDict.map
  function:
    _target_: pie_utils.document.processors.RegexPartitioner
    pattern: ???
  result_document_type: src.document.types.DocumentWithEntitiesRelationsAndLabeledPartitions
