add_reversed_relations:
  _processor_: pytorch_ie.DatasetDict.map
  function:
    _target_: pie_utils.document.processors.ReversedRelationAdder
    label_suffix: _reversed
    # symmetric_relation_labels: Optional[List[str]] = None,
