# use either "plot", "markdown", or "json" as format

# dummy processor that holds general parameters (will not be executed because it does not contain a _processor_)
# useful to enable / disable all statistics at once
collect_statistics:
  labeled_field: ???
  text_field: ???
  _enabled_: true

count_documents:
  _processor_: src.utils.statistics.generic_collect_statistics
  _enabled_: ${dataset.collect_statistics._enabled_}
  format: markdown
  title: number of documents
  aggregate_functions:
    - sum
  measure:
    _target_: src.utils.statistics.DummyCounter

collect_label_counts:
  _processor_: src.utils.statistics.generic_collect_statistics
  _enabled_: ${dataset.collect_statistics._enabled_}
  format: plot
  title: number of ${dataset.collect_statistics.labeled_field} labels
  aggregate_functions:
    - mean
  measure:
    _target_: src.utils.statistics.LabelCounter
    field: ${dataset.collect_statistics.labeled_field}

collect_label_counts_hist:
  _processor_: src.utils.statistics.generic_collect_statistics
  _enabled_: ${dataset.collect_statistics._enabled_}
  format: plot
  title: ${dataset.collect_statistics.labeled_field} labels distribution
  measure:
    _target_: src.utils.statistics.LabelCounter
    field: ${dataset.collect_statistics.labeled_field}

collect_field_lengths:
  _processor_: src.utils.statistics.generic_collect_statistics
  _enabled_: ${dataset.collect_statistics._enabled_}
  format: markdown
  title: number of characters
  measure:
    _target_: src.utils.statistics.DocumentFieldLengthCounter
    field: ${dataset.collect_statistics.text_field}
#collect_span_lengths:
#  _processor_: src.utils.statistics.generic_collect_statistics
#  _enabled_: ${dataset.collect_statistics._enabled_}
#  format: plot
#  title: ${dataset.collect_statistics.labeled_span_field} lengths distribution
#  measure:
#    _target_: src.utils.statistics.DocumentSpanLengthCounter
#    field: ${dataset.collect_statistics.labeled_span_field}
