rename_splits:
  _processor_: pytorch_ie.DatasetDict.rename_splits
  # dictionary to map from original split names to new split names
  mapping: ???
  # if true, keep all other splits that are not mentioned in the mapping
  keep_other_splits: true
