_target_: pie_datasets.DatasetDict.load_dataset

path: dataset_builders/pie/conll2003
## to use the script from the HuggingFace Hub instead of the local version:
# path: pie/conll2003
# revision: 91cdf58a1e4c66fd835749674c7eece8539c1ca9
