# Simple preprocessing pipeline that loads conll2003 and allows to select a subset of documents. Uses all
# documents per default.

# Usage:
# Just use dataset=conll2003_select_n and set any "stop" parameter,
# e.g. dataset.select_n.stop=5 to take only 5 train documents. See _select_n.yaml for further options.

defaults:
  - conll2003_base
  - _collect_statistics

collect_statistics:
  labeled_field: entities
  text_field: text
