_target_: src.utils.execute_pipeline
input:
  _target_: pie_datasets.DatasetDict.load_dataset
  # TODO: switch back to remote version when available
  path: dataset_builders/pie/drugprot
  name: drugprot_source
