_target_: src.utils.dataset.from_hf_dataset
document_type: ??? # src.taskmodules.extractive_question_answering.ExtractiveQADocument
hf_dataset:
  _target_: datasets.load_dataset
  path: json
  data_files:
    test: ${document_path}
