# @package _global_

defaults:
  - _self_
  - dataset: from_serialized_documents.yaml
  - metric: f1.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

pipeline_type: "document_evaluation"

print_config: True
ignore_warnings: True

seed: null

name: "default"

# If defined, evaluate only these splits of the dataset. Note, that per default the data from the
# document_path gets loaded to the "test" split of the dataset when using
# dataset=from_serialized_documents (see the respective dataset config for details).
# splits:
#   - train
#   - test

tags: ["dev"]
