# @package _global_

defaults:
  - _self_
  - dataset: conll2003
  - datamodule: default
  - taskmodule: from_pretrained
  - model: from_pretrained
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

pipeline_type: "evaluation"

name: "default"

tags: ["dev"]

ignore_warnings: False

print_config: True

seed: null

# This should be the value of save_dir from the train config
# or the url to huggingface hub where the taskmodule and model was pushed to.
# It is used in the from_pretrained taskmodule and model configs.
model_name_or_path: pie/example-ner-spanclf-conll03

# Per default, the model is loaded with .from_pretrained() which already loads the weights.
# However, ckpt_path can be used to load different weights from any checkpoint.
ckpt_path: null
