# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - dataset: conll2003
  - datamodule: conll2003
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# this should be the value of save_dir from the train config
# or the url to huggingface hub where the taskmodule and model was pushed to
pretrained_model_name_or_path: ???

# specify the taskmodule
taskmodule:
  _target_: pytorch_ie.taskmodules.TransformerTokenClassificationTaskModule.from_pretrained
  pretrained_model_name_or_path: ${pretrained_model_name_or_path}

# specify the model
model:
  _target_: pytorch_ie.models.transformer_token_classification.TransformerTokenClassificationModel.from_pretrained
  pretrained_model_name_or_path: ${pretrained_model_name_or_path}

# to override model weights with content of a checkpoint
ckpt_path: null