# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - dataset: ???
  - datamodule: default
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# this should be the value of save_dir from the train config
# or the url to huggingface hub where the taskmodule and model was pushed to
model_name_or_path: ???

# specify the taskmodule
taskmodule:
  _target_: pytorch_ie.auto.AutoTaskModule.from_pretrained

# specify the model
model:
  _target_: pytorch_ie.auto.AutoModel.from_pretrained

# to override model weights with content of a checkpoint
ckpt_path: null
