# @package _global_

defaults:
  - _self_
  - dataset: conll2003
  - datamodule: default
  - callbacks: null
  - logger: null
  - trainer: default.yaml
  - hydra: default.yaml
  - paths: default.yaml
  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

task_name: "eval"

name: "default"

# tags to help you identify your experiments
# (you can overwrite this in experiment configs)
tags: ["dataset=conll2003", "model=transformer_token_classification"]

ignore_warnings: False

print_config: True

# passing checkpoint path is necessary for evaluation
ckpt_path: null

seed: null

# this should be the value of save_dir from the train config
# or the url to huggingface hub where the taskmodule and model was pushed to
model_name_or_path: pie/example-ner-spanclf-conll03

# specify the taskmodule
taskmodule:
  _target_: pytorch_ie.auto.AutoTaskModule.from_pretrained

# specify the model
model:
  _target_: pytorch_ie.auto.AutoModel.from_pretrained
