# @package _global_

# overfits to 3 batches

defaults:
  - default.yaml
  # Disable the early stopping callback because no val metrics
  # are available when overfit_batches is set.
  - override /callbacks: none

trainer:
  max_epochs: 20
  overfit_batches: 3
