# This workflow will install PyTorch for CPU and other Python dependencies and calls pre-commit.

name: pre-commit

on:
  pull_request: {}
  push:
    branches: main
    tags: "*"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: show previous workflow conclusion
        run: echo ${{ github.event.workflow_run.conclusion }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install -r requirements.txt
      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Execute pre-commit
        uses: pre-commit/action@v3.0.1
